{% set name = "matspy" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matspy-{{ version }}.tar.gz
  sha256: da4a1b80eda1c56b72eacc390887fa5cc155af882121567f2d059c6a56bec0d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - matplotlib-base

test:
  imports:
    - matspy
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - scipy
    - python-graphblas
    - sparse
  source_files:
    - tests/

about:
  home: https://github.com/alugowski/matspy
  summary: Sparse matrix spy plot and sparkline renderer that works with Jupyter.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - alugowski
